;;;=========================================================================;;;
;;; Copyright 2020 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Big2Small.                                         ;;;
;;;                                                                         ;;;
;;; Big2Small is free software: you can redistribute it and/or modify it    ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Big2Small is distributed in the hope that it will be useful, but        ;;;
;;; WITHOUT ANY WARRANTY; without even the implied warranty of              ;;;
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU       ;;;
;;; General Public License for more details.                                ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Big2Small.  If not, see <http://www.gnu.org/licenses/>.            ;;;
;;;=========================================================================;;;

CHARMAP " ", $00
CHARMAP "A", $01
CHARMAP "B", $02
CHARMAP "C", $03
CHARMAP "D", $04
CHARMAP "E", $05
CHARMAP "F", $06
CHARMAP "G", $07
CHARMAP "H", $08
CHARMAP "I", $09
CHARMAP "J", $0a
CHARMAP "K", $0b
CHARMAP "L", $0c
CHARMAP "M", $0d
CHARMAP "N", $0e
CHARMAP "O", $0f
CHARMAP "P", $10
CHARMAP "Q", $11
CHARMAP "R", $12
CHARMAP "S", $13
CHARMAP "T", $14
CHARMAP "U", $15
CHARMAP "V", $16
CHARMAP "W", $17
CHARMAP "X", $18
CHARMAP "Y", $19
CHARMAP "Z", $1a
CHARMAP "a", $1b
CHARMAP "b", $1c
CHARMAP "c", $1d
CHARMAP "d", $1e
CHARMAP "e", $1f
CHARMAP "f", $20
CHARMAP "g", $21
CHARMAP "h", $22
CHARMAP "i", $23
CHARMAP "j", $24
CHARMAP "k", $25
CHARMAP "l", $26
CHARMAP "m", $27
CHARMAP "n", $28
CHARMAP "o", $29
CHARMAP "p", $2a
CHARMAP "q", $2b
CHARMAP "r", $2c
CHARMAP "s", $2d
CHARMAP "t", $2e
CHARMAP "u", $2f
CHARMAP "v", $30
CHARMAP "w", $31
CHARMAP "x", $32
CHARMAP "y", $33
CHARMAP "z", $34
CHARMAP "0", $35
CHARMAP "1", $36
CHARMAP "2", $37
CHARMAP "3", $38
CHARMAP "4", $39
CHARMAP "5", $3a
CHARMAP "6", $3b
CHARMAP "7", $3c
CHARMAP "8", $3d
CHARMAP "9", $3e
CHARMAP ".", $3f
CHARMAP ",", $40
CHARMAP "!", $41
CHARMAP "?", $42
CHARMAP "`", $43
CHARMAP "'", $44
CHARMAP "-", $45
CHARMAP "*", $46
CHARMAP ">", $47
CHARMAP "=", $48
CHARMAP "|", $49
CHARMAP "+", $4a

;;;=========================================================================;;;
