;;;=========================================================================;;;
;;; Copyright 2020 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Big2Small.                                         ;;;
;;;                                                                         ;;;
;;; Big2Small is free software: you can redistribute it and/or modify it    ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Big2Small is distributed in the hope that it will be useful, but        ;;;
;;; WITHOUT ANY WARRANTY; without even the implied warranty of              ;;;
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU       ;;;
;;; General Public License for more details.                                ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Big2Small.  If not, see <http://www.gnu.org/licenses/>.            ;;;
;;;=========================================================================;;;

DIALOG_ELEPHANT_EYES_OPEN   EQU 0
DIALOG_ELEPHANT_EYES_CLOSED EQU 1
DIALOG_GOAT_MOUTH_CLOSED    EQU 2
DIALOG_GOAT_MOUTH_OPEN      EQU 3
DIALOG_MOUSE                EQU 4
DIALOG_END                  EQU 5

DIALOG_TEXT_NEWLINE EQU $fe
DIALOG_TEXT_EOF     EQU $ff

;;;=========================================================================;;;
